name: CI - Validação do Portfólio

on:
  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest



    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Verificar existência do index.html
        run: |
          if [ ! -f index.html ]; then
            echo "ERRO: index.html não encontrado!"
            exit 1
          fi

